alg = input('Digite algo: ')
print(type(alg))
print('É alphanumerico?', alg.isalnum())
print('É alpha?', alg.isalpha())
print('É decimal?', alg.isdecimal())
print('É um digito?', alg.isdigit())
print('É uma identificaçao?', alg.isidentifier())
print('É minusculo?', alg.islower())
print('É um numero?', alg.isnumeric())
print('É mostravel na tela?', alg.isprintable())